---
branches:
- main
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/github"
- "@semantic-release/npm"
- - "@semantic-release/changelog"
  - changelogFile: docs/CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - package.json
    - docs/CHANGELOG.md
    message: |-
      chore(release): ${nextRelease.version} [skip ci]

      ${nextRelease.notes}
